export const FETCH_MORE_VIDEO = "FETCH_MORE_VIDEO";
export const FETCH_NEW_LIST_VIDEO = "FETCH_NEW_LIST_VIDEO";
export const CHANGE_REGION = "CHANGE_REGION";
export const FETCH_LIST_USER_VIDEO = "FETCH_LIST_USER_VIDEO";
export const GET_USER_INFO = "GET_USER_INFO";
export const SET_LOAD_MORE_VIDEO = "SET_LOAD_MORE_VIDEO";